-- ════════════════════════════════════════════════════════════════════════════
--  SRMC SMS Blast System — Database Schema
--  SQLite DDL (Data Definition Language)
--
--  Engine:    SQLite 3.x (via sql.js WASM)
--  Source:    packages/server/db.js  (initDb function)
--
--  This file mirrors the exact schema created by the application code,
--  including both the initial CREATE TABLE statements and the migration
--  ALTER TABLE ADD COLUMN statements. Indexes that reference migration-added
--  columns are created after the migrations run.
--
--  ⚠ DO NOT EDIT THIS FILE DIRECTLY — update db.js first, then sync here.
-- ════════════════════════════════════════════════════════════════════════════

-- ── Users (agents, admins, super admins) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name  TEXT,
    role          TEXT NOT NULL DEFAULT 'agent',
    active        INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_users_role          ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_role_active   ON users(role, active);


-- ── Gateways (Android SMS transceiver devices) ──────────────────────────
CREATE TABLE IF NOT EXISTS gateways (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    url         TEXT NOT NULL,
    token       TEXT,
    sim_carrier TEXT,
    status      TEXT DEFAULT 'unknown',
    last_beat   TEXT,
    last_online TEXT,
    device_info TEXT,
    sent_today  INTEGER DEFAULT 0,
    active      INTEGER DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_gateways_status ON gateways(status);

-- Migration-added columns (ALTER TABLE ADD COLUMN):
--   last_online       TEXT
--   device_info       TEXT
--   mode              TEXT DEFAULT 'push'
--   last_poll         TEXT
--   number            TEXT
--   consecutive_fails INTEGER DEFAULT 0
--   number2           TEXT
--   sim2_carrier      TEXT
--   turbo_enabled     INTEGER DEFAULT 0
--   delivery_fails    INTEGER DEFAULT 0
--   last_error        TEXT

-- Created AFTER migrations (since 'mode' is migration-added):
-- CREATE INDEX IF NOT EXISTS idx_gateways_active_mode ON gateways(active, mode);


-- ── Gateway authentication tokens ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS gateway_tokens (
    id         TEXT PRIMARY KEY,
    gateway_id TEXT NOT NULL,
    token      TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_gateway_tokens_gateway_id ON gateway_tokens(gateway_id);


-- ── Campaigns (broadcast grouping) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS campaigns (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    owner_id   TEXT,
    status     TEXT DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_campaigns_owner_id ON campaigns(owner_id);


-- ── SMS Templates ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS templates (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    body        TEXT NOT NULL,
    category    TEXT DEFAULT 'transactional',
    variables   TEXT DEFAULT '[]',
    created_by  TEXT,
    use_count   INTEGER DEFAULT 0,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_templates_created_by ON templates(created_by);


-- ── Broadcasts (bulk send operations) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS broadcasts (
    id           TEXT PRIMARY KEY,
    agent_id     TEXT,
    campaign_id  TEXT,
    template_id  TEXT,
    gateway_id   TEXT,
    gateway_ids  TEXT NOT NULL DEFAULT '[]',
    distribution TEXT NOT NULL DEFAULT 'round-robin',
    message      TEXT NOT NULL,
    recipients   TEXT NOT NULL,
    total        INTEGER DEFAULT 0,
    sent         INTEGER DEFAULT 0,
    failed       INTEGER DEFAULT 0,
    status       TEXT DEFAULT 'pending',
    delay_ms     INTEGER DEFAULT 6000,
    started_at   TEXT,
    completed_at TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_broadcasts_agent_id     ON broadcasts(agent_id);
CREATE INDEX IF NOT EXISTS idx_broadcasts_status       ON broadcasts(status);
CREATE INDEX IF NOT EXISTS idx_broadcasts_created_at   ON broadcasts(created_at);
CREATE INDEX IF NOT EXISTS idx_broadcasts_campaign_id  ON broadcasts(campaign_id);

-- Migration-added columns:
--   gateway_ids   TEXT DEFAULT '[]'
--   distribution  TEXT DEFAULT 'round-robin'


-- ── Messages (individual SMS records) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    id           TEXT PRIMARY KEY,
    broadcast_id TEXT,
    to_number    TEXT NOT NULL,
    message      TEXT NOT NULL,
    status       TEXT DEFAULT 'queued',
    error        TEXT,
    gateway_id   TEXT,
    sent_at      TEXT,
    created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_messages_broadcast_id       ON messages(broadcast_id);
CREATE INDEX IF NOT EXISTS idx_messages_gateway_id_status  ON messages(gateway_id, status);
CREATE INDEX IF NOT EXISTS idx_messages_to_number          ON messages(to_number);
CREATE INDEX IF NOT EXISTS idx_messages_status             ON messages(status);
CREATE INDEX IF NOT EXISTS idx_messages_sent_at            ON messages(sent_at);


-- ── Inbound SMS (replies from recipients) ──────────────────────────────
CREATE TABLE IF NOT EXISTS inbound (
    id          TEXT PRIMARY KEY,
    from_number TEXT NOT NULL,
    body        TEXT NOT NULL,
    flag        TEXT,
    read_at     TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_inbound_created_at  ON inbound(created_at);
CREATE INDEX IF NOT EXISTS idx_inbound_read_at     ON inbound(read_at);

-- Migration-added columns:
--   agent_id  TEXT

-- Created AFTER migrations (since 'agent_id' is migration-added):
-- CREATE INDEX IF NOT EXISTS idx_inbound_agent_id ON inbound(agent_id);


-- ── Activity Log (audit trail) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activity (
    id         TEXT PRIMARY KEY,
    user_id    TEXT,
    action     TEXT NOT NULL,
    detail     TEXT,
    level      TEXT DEFAULT 'info',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_activity_user_id    ON activity(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON activity(created_at);
CREATE INDEX IF NOT EXISTS idx_activity_action     ON activity(action);

-- Migration-added columns:
--   campaign_id TEXT


-- ── Settings (key-value configuration) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT
);


-- ════════════════════════════════════════════════════════════════════════════
--  Default Seed Data
-- ════════════════════════════════════════════════════════════════════════════

-- The admin user is NOT seeded here. It is created at runtime by
-- ensureAdminAccount() in db.js, using either ADMIN_PASSWORD env
-- or a random password written to INITIAL_ADMIN.txt.

INSERT OR IGNORE INTO settings (key, value) VALUES ('org_name',                        'SRMC Credit Collection Services');
INSERT OR IGNORE INTO settings (key, value) VALUES ('sender_id',                       'SRMCCS');
INSERT OR IGNORE INTO settings (key, value) VALUES ('delay',                           '6000');
INSERT OR IGNORE INTO settings (key, value) VALUES ('window_start',                    '00:00');
INSERT OR IGNORE INTO settings (key, value) VALUES ('window_end',                      '23:59');
INSERT OR IGNORE INTO settings (key, value) VALUES ('ngrok_url',                       '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('daily_cap',                       '10000');
INSERT OR IGNORE INTO settings (key, value) VALUES ('max_concurrent_broadcasts',        '0');
INSERT OR IGNORE INTO settings (key, value) VALUES ('max_broadcasts_per_agent',         '5');
INSERT OR IGNORE INTO settings (key, value) VALUES ('max_recipients_per_broadcast',     '0');
INSERT OR IGNORE INTO settings (key, value) VALUES ('max_broadcast_duration_minutes',   '0');
INSERT OR IGNORE INTO settings (key, value) VALUES ('max_broadcasts_per_day_per_agent', '0');
INSERT OR IGNORE INTO settings (key, value) VALUES ('broadcasts_globally_paused',       'false');
INSERT OR IGNORE INTO settings (key, value) VALUES ('turbo_delay',                     '100');
INSERT OR IGNORE INTO settings (key, value) VALUES ('turbo_batch_size',                 '5');
INSERT OR IGNORE INTO settings (key, value) VALUES ('timezone',                        'Asia/Manila');
INSERT OR IGNORE INTO settings (key, value) VALUES ('public_url',                      '');


-- ════════════════════════════════════════════════════════════════════════════
--  Migration Notes
--
--  The application code (db.js) uses ALTER TABLE ADD COLUMN statements
--  wrapped in try/catch to add columns to existing databases. These
--  migrations run AFTER the initial CREATE TABLE IF NOT EXISTS and index
--  creation.
--
--  Two indexes are created AFTER migrations because they reference
--  migration-added columns:
--    idx_gateways_active_mode  → depends on 'mode' column   (gateways)
--    idx_inbound_agent_id       → depends on 'agent_id' column (inbound)
--
--  All other indexes reference columns that exist in the original
--  CREATE TABLE statements and are safe to create up front.
-- ════════════════════════════════════════════════════════════════════════════
